### ISSUE TITLE
brcmfmac43430-sdio.clmblob  

### ISSUE THREAD

**Issue by chance2006** [RPi-Distro/firmware-nonfree#15]
Dear Sir/lady:
I couldn't found wlano0 with my raspberry Pi3.I saw some explain on https://wiki.ubuntu.com/ARM/RaspberryPi. But I couldn't found brcmfmac43430-sdio.clmblob  on web.
Could you kindly share this file ?Or other solution? 
Thanks very much!
Best Regards!
Bob

**Comment by chance2006** [comment]
Dear Sir/Lady
I'm sorry for my misspelling ,the fie is brcmfmac43430-sdio.clm_blob. Thanks again!
Best regards!
Bob

**Comment by pelwell** [comment]
The file does not exist because the content is already part of brcmfmac43430-sdio.bin. However, the kernel does not know this, which is why there is a warning message about it being missing.
