### ISSUE TITLE
License clarification - Broadcom vs Cypress

### ISSUE THREAD

**Issue by Entropy512** [RPi-Distro/firmware-nonfree#21]
I have seen enough concerns raised by others that indicate that perhaps there needs to be some clarification regarding the licensing of Broadcom/Cypress FMAC binary firmwares.

Specifically, even though I am personally confident that @pelwell and @XECDesign are authorized to redistribute the files in question (especially since Phil has used signed-off-by commits), there are others who raise an objection to some of the binaries here as far as whether or not they can use them due to redistribution licensing questions.

I actually do myself have a small concern - https://github.com/RPi-Distro/firmware-nonfree/blob/bullseye/debian/config/brcm80211/LICENSE was added six years ago, and the Cypress split-off is significantly more recent than that.  The LICENSE file references Broadcom with no mention of Cypress, and https://github.com/RPi-Distro/firmware-nonfree/commits/bullseye/debian/config/brcm80211/cypress was added nearly five years after that LICENSE file by commit https://github.com/RPi-Distro/firmware-nonfree/commit/dcea7a3c12490f264033e489f8c6b56032d9f249#diff-9d8885077e70f76547806fa3d012315739075d6e10ae5ccc3833845c4fd6e32b which lacks a signed-off-by: line that is present in many of Phil's most recent commits.  This lack of an SoB line has been raised by others as concerning enough to merit not permitting the contents of this repository to be used by at least one downstream project.  Personally, I would prefer to be able to point to this repo when building for Raspberry Pi targets in order to use the board-specific clm_blob files here.

Could you please confirm/clarify that all content in https://github.com/RPi-Distro/firmware-nonfree/tree/bullseye/debian/config/brcm80211 was placed there by those legally authorized to do so, under the license currently present there?

**Comment by pelwell** [comment]
As Raspberry Pi's new github.io page (https://raspberrypi.github.io/) shows, `RPi-Distro` is an official Raspberry Pi organisation (as is `raspberrypi-ui`). All content is placed there - either directly or by merging someone else's Pull Request - by employees of Raspberry Pi Ltd. In particular, the `firmware-nonfree` repo contains firmware that we are authorized to make available under the licences there.

**Comment by Entropy512** [comment]
In my opinion, https://github.com/RPi-Distro/firmware-nonfree/commit/69f857b796fcf7ec78e794c5f56f164e1c0998bf closes this issue.  Hopefully others agree.
