### ISSUE TITLE
brcmfmac firmware load failing for Raspberry Pi Zero 2W

### ISSUE THREAD

**Issue by fhunleth** [RPi-Distro/firmware-nonfree#25]
I'm getting the following errors on a Raspberry Pi Zero 2W:

```
[    5.754866] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43436-sdio for chip BCM43430/2
[    5.755074] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43436-sdio.raspberrypi,model-zero-2-w.bin failed with error -2
[    5.786347] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43436-sdio.txt failed with error -2
[    5.786468] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430b0-sdio for chip BCM43430/2
[    5.786573] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430b0-sdio.raspberrypi,model-zero-2-w.bin failed with error -2
[    5.786664] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430b0-sdio.bin failed with error -2
```

I worked around this by adding the following symlinks in `/lib/firmware/brcm`:

```
brcmfmac43436-sdio.raspberrypi,model-zero-2-w.bin -> brcmfmac43436f-sdio.bin
brcmfmac43436-sdio.txt -> brcmfmac43436f-sdio.txt
```

WiFi seems to be working in my tests so far.

This is on a Buildroot configuration that uses Linux 5.15 as sourced from https://github.com/raspberrypi/linux/tree/rpi-5.15.y.

Do you know if these symlinks are the right ones to add? Or is something else going on and they shouldn't be needed?

**Comment by pelwell** [comment]
Your symlink looks correct to me, but it shouldn't be necessary. The debian installation scripts are a bit confused about the handling of the many WLAN device variants, but @XECDesign is on the case.

**Comment by fhunleth** [comment]
Thanks for the quick response! I had neglected to look at the Debian scripts for more symlinks when using this git repository with Buildroot. That was it.
