### ISSUE TITLE
brcmfmac43455 issues using wpa_cli with recent update 

### ISSUE THREAD

**Issue by tswaehn** [RPi-Distro/firmware-nonfree#6]
I did notice issues when I use the `$ wpa_cli -i wlan0 status`
(using rpi3b+)

Since the commit 4ee44af381d55bc2221cf80c1433842a48ed09e1

the `wpa_cli` is no longer returning proper status feedback. Instead it complains about not beeing able to find global ressource wlan0.

```
$ sudo wpa_cli -i wlan0 status
Failed to connect to non-global ctrl_ifname: wlan0  error: No such file or directory
```

switching back to the older version ( e18f47df5728a89a424df0e00d113decd64ae526)  immediatly makes `wpa_cli` return proper status feedback.

**update 1**

- rpi3b+
- stretch at 32bit

**Comment by XECDesign** [comment]
Works for me on Raspbian. Did you also add the new clm_blob file?

**Comment by tswaehn** [comment]
Yes.

I did use stretch 32bit on a rpi3b+ having the issue.

**Comment by pelwell** [comment]
It works for me as well. What's in your wpa_supplicant.conf?

**Comment by pelwell** [comment]
In particular, it should include a country code, e.g.:
```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=GB

network={
        ssid=...
```

**Comment by tswaehn** [comment]
That’s in for sure. Please note I am using stretch 32bit. 

Strange thing is that old firmware runs perfect. But new one is not working. Two identical images - just replacing the firmware changes the behaviour.

Maybe there is another thing that I am missing. Ex a newer version of wpa_supplicant

**Comment by tswaehn** [comment]
BTW. The Network section is set to non existing ssid by purpose. Because I am connecting through wpa_cli dynamically.

Please confirm that connecting wpa_cli is running fine on your stretch  32bit with new firmware.

**Comment by pelwell** [comment]
Do you known which Stretch image you installed, so I can match it?

**Comment by tswaehn** [comment]
To save your time. Which Image and RPI Version did you use?
I can do the test here :)

**Comment by pelwell** [comment]
The "Stretch" comment is the clincher. There appears to be a dependency between the firmware and the kernel version (or it's just possible it's the firmware). Installing the latest kernel with `sudo rpi-update` should fix the problem for you.

If you've updated Stretch using apt/apt-get and ended up with an old kernel and a new WiFi firmware that don't work together then we have a problem. If, however, you've just patched Stretch with the new firmware then it's reasonable to expect (now that we know) that users update both together.

**Comment by XECDesign** [comment]
The wifi firmware package hasn't been updated in Stretch. So you'd only end up in the situation if you've copied it manually then.

**Comment by tswaehn** [comment]
I am actually building my own stretch image and thought to have used the latest kernel and did copy the latest firmware. So following your information, i am actually not using the latest kernel then. 

Let me double check...

**Comment by XECDesign** [comment]
Feel free to re-open if you can provide instructions on how to reproduce the problem starting with a clean Buster image.

**Comment by tswaehn** [comment]
Indeed - my fault: using kernel 4.14.x with latest firmware doesnt work.

Sorry for bugging.
